export const ROUTES_CONSTANT = {
  CONTACTS: "/dashboard/contacts",
  REFERRALS: "/dashboard/referrals",
  USERS: "/dashboard/users",
  REQUESTS: "/dashboard/requests",
  ANALYTICS: "/dashboard/analytics",
  SETTINGS: "/dashboard/settings",
  DASHBOARD: "/dashboard",
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  VERIFY_EMAIL: "/verify-email",
  VERIFY_OTP: "/verify-otp",
  ROOT: "/",
  NEW_REQUEST: "/dashboard/requests/new",
  NEW_CONTACT: "/dashboard/contacts/new",
  NEW_REFERRAL: "/dashboard/referrals/new",
  NEW_USER: "/dashboard/users/new",
  NEW_ANALYTICS: "/dashboard/analytics/new",
  NEW_SETTINGS: "/dashboard/settings/new",
};
